# Generated by Django 4.0 on 2022-03-23 20:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_order_productorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
