# Generated by Django 4.0 on 2022-03-28 20:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_price'),
        ('selections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='selection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selection',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.DeleteModel(
            name='UserSelection',
        ),
        migrations.AddField(
            model_name='productselection',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='selections.selection'),
        ),
    ]
